### ISSUE TITLE
Execution Failes

### ISSUE THREAD

**Issue by siddharth7997** [victordibia/data2vis#1]
.
Instructions for updating:
Use tf.cast instead.
Traceback (most recent call last):
  File "webserver.py", line 149, in <module>
    model=model, input_pipeline=input_pipeline_infer, batch_size=batch_size)
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\inference\inference.py", line 54, in create_inference_graph
    return model(features=features, labels=labels, params=None)
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\models\model_base.py", line 146, in __call__
    return self._build(features, labels, params)
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\models\seq2seq_model.py", line 297, in _build
    encoder_output = self.encode(features, labels)
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\graph_utils.py", line 38, in func_wrapper
    return templated_func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 368, in __call__
    return self._call_func(args, kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 311, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\models\basic_seq2seq.py", line 109, in encode
    return encoder_fn(source_embedded, features["source_len"])
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\graph_module.py", line 57, in __call__
    return self._template(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 311, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\encoders\encoder.py", line 49, in _build
    return self.encode(inputs, *args, **kwargs)
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\encoders\rnn_encoder.py", line 135, in encode
    cell_fw = training_utils.get_rnn_cell(**self.params["rnn_cell"])
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\training\utils.py", line 157, in get_rnn_cell
    cell = cell_from_spec(cell_class, cell_params)
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\training\utils.py", line 123, in cell_from_spec
    are: {}""".format(key, cell_class.__name__, cell_args))
ValueError: num_units is not a valid argument for LSTMCell class. Available arguments
          are: set()

originally defined at:
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\models\basic_seq2seq.py", line 108, in encode
    encoder_fn = self.encoder_class(self.params["encoder.params"], self.mode)
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\encoders\rnn_encoder.py", line 119, in __init__
    super(BidirectionalRNNEncoder, self).__init__(params, mode, name)
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\encoders\encoder.py", line 45, in __init__
    GraphModule.__init__(self, name)
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\graph_module.py", line 44, in __init__
    self._template = tf.make_template(name, self._build, create_scope_now_=True)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 154, in make_template
    **kwargs)

originally defined at:
  File "C:\Users\siddh\OneDrive\Documents\data2vis-master\seq2seq\graph_utils.py", line 37, in func_wrapper
    templated_func = tf.make_template(name_, func)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 154, in make_template
    **kwargs)

**Comment by victordibia** [comment]
What command produces this? Can you also share the full error?

**Comment by minipig1996** [comment]
>python -m unittest seq2seq.test.pipeline_test
when I exe it,the error exist.

**Comment by sczhu2024** [comment]
@victordibia 
python -m unittest seq2seq.test.pipeline_test
when I exe it,the error exist.
