### ISSUE TITLE
How to overcome this error to get visualization output

### ISSUE THREAD

**Issue by chkiran219** [victordibia/data2vis#2]
![image](https://user-images.githubusercontent.com/30895951/54478597-eabb7400-4839-11e9-978f-c14f87d7841f.png)
![image](https://user-images.githubusercontent.com/30895951/54478625-438b0c80-483a-11e9-929d-cf1883bc0494.png)

127.0.0.1 - - [16/Mar/2019 22:31:09] "[37mGET /static/js/seqviz.js?_=1552755669948 HTTP/1.1[0m" 200 -
127.0.0.1 - - [16/Mar/2019 22:31:11] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [16/Mar/2019 22:31:11] "[33mGET /static/assets/model.jpg HTTP/1.1[0m" 404 -
127.0.0.1 - - [16/Mar/2019 22:31:12] "[37mGET /static/js/seqviz.js?_=1552755671765 HTTP/1.1[0m" 200 -
127.0.0.1 - - [16/Mar/2019 22:31:15] "[37mGET /testdata HTTP/1.1[0m" 200 -
2019-03-16 22:31:16.615159: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-03-16 22:31:17.172443: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: Read fewer bytes than requested
127.0.0.1 - - [16/Mar/2019 22:31:17] "[1m[35mPOST /inference HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\data2vis-master\webserver.py", line 267, in inference
    run_inference()
  File "D:\data2vis-master\webserver.py", line 170, in run_inference
    session_creator=session_creator, hooks=hooks) as sess:
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\monitored_session.py", line 816, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\monitored_session.py", line 539, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1002, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1007, in _create_session
    return self._sess_creator.create_session()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\monitored_session.py", line 696, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\monitored_session.py", line 467, in create_session
    init_fn=self._scaffold.init_fn)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\session_manager.py", line 287, in prepare_session
    init_fn(sess)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\monitored_session.py", line 163, in <lambda>
    self._init_fn = lambda sess: init_fn(self, sess)
  File "D:\data2vis-master\webserver.py", line 164, in session_init_op
    saver.restore(sess, checkpoint_path)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: Read fewer bytes than requested
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\socketserver.py", line 724, in __init__
    self.handle()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\werkzeug\serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\werkzeug\serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\werkzeug\serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\werkzeug\serving.py", line 260, in execute
    for data in application_iter:
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\werkzeug\debug\__init__.py", line 288, in debug_application
    app_iter = self.app(environ, start_response)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "webserver.py", line 267, in inference
    run_inference()
  File "webserver.py", line 158, in run_inference
    saver = tf.train.Saver()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\saver.py", line 1338, in __init__
    self.build()
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\saver.py", line 835, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\saver.py", line 472, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\training\saver.py", line 886, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1462, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "C:\Users\Admin\Anaconda3\envs\Another\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): Read fewer bytes than requested
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
127.0.0.1 - - [16/Mar/2019 22:31:20] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -

**Comment by victordibia** [comment]
Hi,

> Caused by op 'save/RestoreV2', 

This is likely as a result of differences in Tensorflow versions . I would suggest you try tensorflow `1.10` or below (thats whats used to export the models).

-V.

**Comment by chkiran219** [comment]
Hello, 
Thanks for the response. 
I had already tried it using various versions of TensorFlow it didn't work (including 1.10), and may I know the exact steps to execute the code please ?
Like I had installed all the requirements and changed the "host address" to 'Localhost' in the "webserver.py" and executed it using Anaconda software, did I miss anything ? or should I try executing it on Linux ? 
Please respond back, Thanks.

**Comment by chkiran219** [comment]
Can I know your System Specifications which you've used to execute this project? And the model is already trained right ?

**Comment by victordibia** [comment]
Thanks for the note @chkiran219 

For inference I used a MacBook Pro 2.4ghz, Python 3, TF 1.10.

One final thing ... the  pretrained model is stored on GitHub  with Git lfs. Ensure you use git clone lfs and have the right model file size when you clone the repo.

What is the size of `vizmodel/model.ckpt-20000.data-00000-of-00001` on your local machine?

-V.

**Comment by victordibia** [comment]
Closing if you do not have any other issues.
