### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by ghostaccount737** [victordibia/data2vis#4]
```
 python3 -m bin.infer   --tasks "
    - class: DecodeText
      params:
        delimiter: '' "   --model_dir vizmodel   --model_params "
    inference.beam_search.beam_width: 2"   --input_pipeline "
    class: ParallelTextInputPipeline
    params:
      source_delimiter: ''
      target_delimiter: ''
      source_files:
        -  test.txt "
/home/vinay/data2vis/seq2seq/configurable.py:62: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(item)
INFO:tensorflow:Creating ParallelTextInputPipeline in mode=infer
INFO:tensorflow:
ParallelTextInputPipeline:
  num_epochs: 1
  shuffle: false
  source_delimiter: ''
  source_files:
  - test.txt
  target_delimiter: ''
  target_files: []

INFO:tensorflow:Creating AttentionSeq2Seq in mode=infer
INFO:tensorflow:
AttentionSeq2Seq:
  attention.class: seq2seq.decoders.attention.AttentionLayerDot
  attention.params:
    num_units: 512
  bridge.class: seq2seq.models.bridges.ZeroBridge
  bridge.params: {}
  decoder.class: seq2seq.decoders.AttentionDecoder
  decoder.params:
    max_decode_length: 2000
    rnn_cell:
      cell_class: LSTMCell
      cell_params:
        num_units: 512
      dropout_input_keep_prob: 0.5
      dropout_output_keep_prob: 1.0
      num_layers: 2
  embedding.dim: 512
  embedding.init_scale: 0.04
  embedding.share: false
  encoder.class: seq2seq.encoders.BidirectionalRNNEncoder
  encoder.params:
    rnn_cell:
      cell_class: LSTMCell
      cell_params:
        num_units: 512
      dropout_input_keep_prob: 0.5
      dropout_output_keep_prob: 1.0
      num_layers: 2
  inference.beam_search.beam_width: 2
  inference.beam_search.choose_successors_fn: choose_top_k
  inference.beam_search.length_penalty_weight: 0.0
  optimizer.clip_embed_gradients: 0.1
  optimizer.clip_gradients: 5.0
  optimizer.learning_rate: 0.0001
  optimizer.lr_decay_rate: 0.99
  optimizer.lr_decay_steps: 100
  optimizer.lr_decay_type: ''
  optimizer.lr_min_learning_rate: 1.0e-12
  optimizer.lr_staircase: false
  optimizer.lr_start_decay_at: 0
  optimizer.lr_stop_decay_at: 2147483647
  optimizer.name: Adam
  optimizer.params:
    epsilon: 8.0e-07
  optimizer.sync_replicas: 0
  optimizer.sync_replicas_to_aggregate: 0
  source.max_seq_len: 500
  source.reverse: false
  target.max_seq_len: 500
  vocab_source: sourcedata/vocab.source
  vocab_target: sourcedata/vocab.target

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vinay/data2vis/bin/infer.py", line 130, in <module>
    tf.app.run()
  File "/home/vinay/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/vinay/data2vis/bin/infer.py", line 100, in main
    task = task_cls(tdict["params"])
TypeError: __init__() missing 1 required positional argument: 'callback_func'

```

**Comment by ghostaccount737** [comment]
@victordibia any suggestions ?

**Comment by victordibia** [comment]
Sure ... there was a slight change to the structure of the `DecodeText` task which requires a callback. I have now updated `infer.py` to include this callback.  

Also note that the input text in `test.txt` must be in the transformed input format (ie. string, numeric and date column names are replaced with a short form).

```
{"num0": "0", "num1": "4", "num2": "80", "str0": "female"}
```

The  `forward_norm` method in the `utils/data_utils.py` file can be used to generate this normalized version of any data input. 

If you are not comfortable with Tensorflow, I would recommend that you run this using the webdemo interface.

Can you run the web demo correctly?

-V.

**Comment by ghostaccount737** [comment]
No issues with the web demo 

This works perfectly fine now and will soon get acquainted with TF

**Comment by victordibia** [comment]
Thanks for the update!
Good luck with your Tensorflow journey too!
I am also looking towards rewriting this using the more intuitive Keras api ... but I will need alot of time :( ...

-V.

**Comment by PVinay737** [comment]
All the best with the keras api and will try to contribute to it

**Comment by ghostaccount737** [comment]
All the best with the keras api and will try contributing to it
